name: Build, Test and SonarCloud

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install SonarCloud Scanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Begin SonarCloud analysis
      run: |
        dotnet sonarscanner begin \
        /k:"LucasMIsrael_FinancialControlSystem-Backend-TCC" \
        /o:"lucasmisrael" \
        /d:sonar.host.url="https://sonarcloud.io" \
        /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
        /d:sonar.cs.opencover.reportsPaths="FinancialControlSystem-Backend/FinancialSystem.Test/Coverage/coverage.cobertura.xml"

    - name: Restore
      run: dotnet restore FinancialControlSystem-Backend/FinancialControlSystem.sln

    - name: Build
      run: dotnet build FinancialControlSystem-Backend/FinancialControlSystem.sln --configuration Release

    - name: Create coverage directory
      run: mkdir -p FinancialControlSystem-Backend/FinancialSystem.Test/Coverage

    - name: Test with coverage
      run: dotnet test FinancialControlSystem-Backend/FinancialSystem.Test/FinancialSystem.Test.csproj \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutput=FinancialControlSystem-Backend/FinancialSystem.Test/Coverage/coverage.cobertura.xml \
            /p:CoverletOutputFormat=cobertura

    - name: End SonarCloud analysis
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
