# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core Self-Contained to Azure Web App - finvision-backend

on:
  push:
    branches:
      - Refact # Gatilho para a branch de testes
  workflow_dispatch:

env:
  # Definindo o caminho do projeto Web para simplificar o build
  PROJECT_PATH: FinancialControlSystem-Backend/FinancialSystem.Web/FinancialSystem.Web.csproj
  # O App Service é Windows, então usamos win-x64
  RUNTIME_IDENTIFIER: win-x64
  
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # 1. Restaura e Compila (usando o caminho completo)
      - name: Restore and Build
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      # 2. Publicação CRUCIAL: Adiciona as flags Self-Contained
      - name: dotnet publish (Self-Contained)
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o "${{env.DOTNET_ROOT}}/myapp" --self-contained true -r ${{ env.RUNTIME_IDENTIFIER }} /p:UseAppHost=false

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          
      # O Azure Login e o Deploy-to-WebApp estão corretos com as secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D71E18FF340A4286B72224EA5A29FBA4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7F54467AA2214D99927B635EE735D2B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1CABC8801A8A4707A597E35C2AF4E8C4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'finvision-backend'
          slot-name: 'Production'
          package: . # Aponta para a pasta onde o artefato foi baixado
